# Generated by Django 6.0 on 2025-12-19 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('team1',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='team1_matches',
                                   to='analysis.team')),
                ('team2',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='team2_matches',
                                   to='analysis.team')),
                ('winner',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='wins',
                                   to='analysis.team')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('over', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('match', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='analysis.match')),
                ('batting_team',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='batting_deliveries',
                                   to='analysis.team')),
                ('bowling_team',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='bowling_deliveries',
                                   to='analysis.team')),
            ],
        ),
    ]
