# Generated by Django 6.0 on 2025-12-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='balls',
            new_name='ball',
        ),
    ]
